export const COURT_ALLIANCE_TARGET_COHESION_THRESHOLD = 48;
export const COURT_ALLIANCE_COMBINED_COHESION_THRESHOLD = 104;
export const COURT_ALLIANCE_DURATION_TURNS = 16;
export const MAX_COURT_ALLIANCE_ACTIONS_PER_POLITY = 1;
export const COURT_ALLIANCE_TERMS = '在朝廷议程中互相支持且不以清洗夺取盟友席位';
