import type {
  PolityDefinition,
  PortLinkDefinition,
  RegionDefinition,
  RouteDefinition,
  SeaLaneDefinition,
  SeaZoneDefinition,
} from '../types';

export type {
  PolityDefinition,
  PortLinkDefinition,
  RegionDefinition,
  RouteDefinition,
  SeaLaneDefinition,
  SeaZoneDefinition,
} from '../types';

export const POLITY_DEFINITIONS: readonly PolityDefinition[] = [
  { id: 'p_yan', name: '燕国', shortName: '燕', color: '#8b3e35', capitalRegionId: 'r_yanjing', governmentForm: '王朝', maritimeOrientation: 24 },
  { id: 'p_qi', name: '齐国', shortName: '齐', color: '#3f6f68', capitalRegionId: 'r_qizhou', governmentForm: '王朝', maritimeOrientation: 42 },
  { id: 'p_yong', name: '雍国', shortName: '雍', color: '#9a7339', capitalRegionId: 'r_changan', governmentForm: '王朝', maritimeOrientation: 24 },
  { id: 'p_xuantu', name: '玄菟国', shortName: '玄', color: '#536b82', capitalRegionId: 'r_liaodong', governmentForm: '王朝', maritimeOrientation: 24 },
  { id: 'p_canghai', name: '沧海盟', shortName: '沧', color: '#735b83', capitalRegionId: 'r_guangzhou', governmentForm: '盟约', maritimeOrientation: 72 },
  { id: 'p_minhai', name: '闽海国', shortName: '闽', color: '#457f8c', capitalRegionId: 'r_quanzhou', governmentForm: '王朝', maritimeOrientation: 24 },
  { id: 'p_haedong', name: '海东国', shortName: '海', color: '#78624b', capitalRegionId: 'r_hanjing', governmentForm: '王朝', maritimeOrientation: 24 },
  { id: 'p_yamato', name: '和国', shortName: '和', color: '#9b5f73', capitalRegionId: 'r_yamato', governmentForm: '王朝', maritimeOrientation: 24 },
] as const;

export const REGION_DEFINITIONS: readonly RegionDefinition[] = [
  { id: 'r_yanjing', name: '燕京', x: 500, y: 92, terrain: '平原', climate: '寒温带', river: true, port: false, cityLevel: 4, defense: 34, strategicValue: 10, fertility: 94, populationBase: 190_000, initialControllerId: 'p_yan' },
  { id: 'r_jinmen', name: '津门', x: 570, y: 128, terrain: '海岸', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 26, strategicValue: 9, fertility: 89, populationBase: 155_000, initialControllerId: 'p_yan' },
  { id: 'r_changshan', name: '常山', x: 426, y: 180, terrain: '丘陵', climate: '暖温带', river: false, port: false, cityLevel: 2, defense: 36, strategicValue: 8, fertility: 84, populationBase: 132_000, initialControllerId: 'p_yan' },
  { id: 'r_yecheng', name: '邺城', x: 494, y: 258, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 27, strategicValue: 9, fertility: 103, populationBase: 176_000, initialControllerId: 'p_yan' },
  { id: 'r_jinyang', name: '晋阳', x: 322, y: 183, terrain: '高原', climate: '寒温带', river: true, port: false, cityLevel: 3, defense: 43, strategicValue: 8, fertility: 76, populationBase: 118_000, initialControllerId: 'p_yan' },
  { id: 'r_shangdang', name: '上党', x: 392, y: 264, terrain: '山地', climate: '暖温带', river: false, port: false, cityLevel: 2, defense: 50, strategicValue: 8, fertility: 67, populationBase: 91_000, initialControllerId: 'p_yan' },

  { id: 'r_qizhou', name: '齐州', x: 595, y: 268, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 4, defense: 29, strategicValue: 10, fertility: 108, populationBase: 202_000, initialControllerId: 'p_qi' },
  { id: 'r_qingzhou', name: '青州', x: 680, y: 245, terrain: '丘陵', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 31, strategicValue: 8, fertility: 97, populationBase: 152_000, initialControllerId: 'p_qi' },
  { id: 'r_dengzhou', name: '登州', x: 760, y: 190, terrain: '海岸', climate: '暖温带', river: false, port: true, cityLevel: 2, defense: 33, strategicValue: 9, fertility: 83, populationBase: 102_000, initialControllerId: 'p_qi' },
  { id: 'r_langya', name: '琅琊', x: 662, y: 355, terrain: '海岸', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 28, strategicValue: 8, fertility: 101, populationBase: 159_000, initialControllerId: 'p_qi' },
  { id: 'r_kaifeng', name: '开封', x: 520, y: 342, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 4, defense: 24, strategicValue: 10, fertility: 112, populationBase: 213_000, initialControllerId: 'p_qi' },
  { id: 'r_runan', name: '汝南', x: 535, y: 430, terrain: '平原', climate: '湿热', river: true, port: false, cityLevel: 3, defense: 23, strategicValue: 8, fertility: 113, populationBase: 184_000, initialControllerId: 'p_qi' },

  { id: 'r_luoyang', name: '洛阳', x: 425, y: 342, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 4, defense: 35, strategicValue: 10, fertility: 99, populationBase: 196_000, initialControllerId: 'p_yong' },
  { id: 'r_nanyang', name: '南阳', x: 430, y: 438, terrain: '丘陵', climate: '湿热', river: true, port: false, cityLevel: 3, defense: 31, strategicValue: 8, fertility: 107, populationBase: 171_000, initialControllerId: 'p_yong' },
  { id: 'r_hedong', name: '河东', x: 330, y: 300, terrain: '丘陵', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 37, strategicValue: 8, fertility: 91, populationBase: 139_000, initialControllerId: 'p_yong' },
  { id: 'r_changan', name: '长安', x: 246, y: 354, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 4, defense: 41, strategicValue: 10, fertility: 96, populationBase: 188_000, initialControllerId: 'p_yong' },
  { id: 'r_yanan', name: '延安', x: 205, y: 258, terrain: '高原', climate: '干旱', river: false, port: false, cityLevel: 2, defense: 44, strategicValue: 7, fertility: 61, populationBase: 78_000, initialControllerId: 'p_yong' },
  { id: 'r_lingzhou', name: '灵州', x: 112, y: 226, terrain: '高原', climate: '干旱', river: true, port: false, cityLevel: 2, defense: 38, strategicValue: 8, fertility: 55, populationBase: 72_000, initialControllerId: 'p_yong' },

  { id: 'r_liaoxi', name: '辽西', x: 642, y: 112, terrain: '丘陵', climate: '寒温带', river: false, port: true, cityLevel: 2, defense: 37, strategicValue: 8, fertility: 69, populationBase: 88_000, initialControllerId: 'p_xuantu' },
  { id: 'r_liaodong', name: '辽东', x: 725, y: 91, terrain: '平原', climate: '寒温带', river: true, port: true, cityLevel: 3, defense: 36, strategicValue: 10, fertility: 81, populationBase: 127_000, initialControllerId: 'p_xuantu' },
  { id: 'r_jilin', name: '吉林', x: 812, y: 62, terrain: '丘陵', climate: '寒温带', river: true, port: false, cityLevel: 2, defense: 40, strategicValue: 7, fertility: 66, populationBase: 79_000, initialControllerId: 'p_xuantu' },
  { id: 'r_changbai', name: '长白', x: 864, y: 127, terrain: '山地', climate: '寒温带', river: true, port: false, cityLevel: 1, defense: 53, strategicValue: 7, fertility: 48, populationBase: 52_000, initialControllerId: 'p_xuantu' },
  { id: 'r_pyongyang', name: '平壤', x: 815, y: 202, terrain: '平原', climate: '寒温带', river: true, port: true, cityLevel: 3, defense: 34, strategicValue: 9, fertility: 86, populationBase: 128_000, initialControllerId: 'p_xuantu' },
  { id: 'r_hanjing', name: '汉京', x: 850, y: 286, terrain: '丘陵', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 35, strategicValue: 9, fertility: 93, populationBase: 137_000, initialControllerId: 'p_haedong' },

  { id: 'r_quanzhou', name: '泉州', x: 650, y: 535, terrain: '海岸', climate: '湿热', river: false, port: true, cityLevel: 3, defense: 29, strategicValue: 9, fertility: 105, populationBase: 148_000, initialControllerId: 'p_minhai' },
  { id: 'r_guangzhou', name: '广州', x: 470, y: 578, terrain: '海岸', climate: '湿热', river: true, port: true, cityLevel: 4, defense: 27, strategicValue: 10, fertility: 111, populationBase: 192_000, initialControllerId: 'p_canghai' },
  { id: 'r_hainan', name: '海南', x: 452, y: 668, terrain: '岛屿', climate: '湿热', river: false, port: true, cityLevel: 2, defense: 32, strategicValue: 7, fertility: 101, populationBase: 76_000, initialControllerId: 'p_canghai' },
  { id: 'r_taiwan', name: '台湾', x: 748, y: 578, terrain: '岛屿', climate: '湿热', river: true, port: true, cityLevel: 2, defense: 38, strategicValue: 8, fertility: 107, populationBase: 93_000, initialControllerId: 'p_minhai' },
  { id: 'r_tsukushi', name: '筑紫', x: 870, y: 474, terrain: '岛屿', climate: '暖温带', river: false, port: true, cityLevel: 3, defense: 35, strategicValue: 9, fertility: 92, populationBase: 124_000, initialControllerId: 'p_yamato' },
  { id: 'r_naniwa', name: '浪速', x: 965, y: 406, terrain: '海岸', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 33, strategicValue: 9, fertility: 96, populationBase: 143_000, initialControllerId: 'p_yamato' },

  // V0.2扩展区域：新世界使用48州域；V0.1旧档迁移不会补造这些地区。
  { id: 'r_datong', name: '云中', x: 300, y: 104, terrain: '高原', climate: '寒温带', river: false, port: false, cityLevel: 2, defense: 45, strategicValue: 8, fertility: 62, populationBase: 82_000, initialControllerId: 'p_yan' },
  { id: 'r_hejian', name: '河间', x: 548, y: 205, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 28, strategicValue: 8, fertility: 101, populationBase: 146_000, initialControllerId: 'p_yan' },
  { id: 'r_yuyang', name: '渔阳', x: 585, y: 72, terrain: '丘陵', climate: '寒温带', river: true, port: false, cityLevel: 2, defense: 39, strategicValue: 8, fertility: 76, populationBase: 96_000, initialControllerId: 'p_yan' },

  { id: 'r_donglai', name: '东莱', x: 733, y: 278, terrain: '海岸', climate: '暖温带', river: false, port: true, cityLevel: 2, defense: 32, strategicValue: 8, fertility: 88, populationBase: 112_000, initialControllerId: 'p_qi' },
  { id: 'r_pengcheng', name: '彭城', x: 615, y: 425, terrain: '平原', climate: '湿热', river: true, port: false, cityLevel: 3, defense: 29, strategicValue: 9, fertility: 109, populationBase: 168_000, initialControllerId: 'p_qi' },
  { id: 'r_huaiyang', name: '淮阳', x: 560, y: 492, terrain: '平原', climate: '湿热', river: true, port: false, cityLevel: 2, defense: 24, strategicValue: 7, fertility: 115, populationBase: 151_000, initialControllerId: 'p_qi' },

  { id: 'r_beidi', name: '北地', x: 155, y: 305, terrain: '高原', climate: '干旱', river: false, port: false, cityLevel: 2, defense: 42, strategicValue: 7, fertility: 57, populationBase: 70_000, initialControllerId: 'p_yong' },
  { id: 'r_tianshui', name: '天水', x: 145, y: 395, terrain: '山地', climate: '暖温带', river: true, port: false, cityLevel: 2, defense: 48, strategicValue: 8, fertility: 73, populationBase: 89_000, initialControllerId: 'p_yong' },
  { id: 'r_hanzhong', name: '汉中', x: 285, y: 465, terrain: '山地', climate: '湿热', river: true, port: false, cityLevel: 3, defense: 51, strategicValue: 9, fertility: 96, populationBase: 126_000, initialControllerId: 'p_yong' },
  { id: 'r_shangluo', name: '商洛', x: 345, y: 405, terrain: '山地', climate: '暖温带', river: true, port: false, cityLevel: 2, defense: 46, strategicValue: 8, fertility: 79, populationBase: 93_000, initialControllerId: 'p_yong' },

  { id: 'r_shenyang', name: '沈州', x: 690, y: 145, terrain: '平原', climate: '寒温带', river: true, port: false, cityLevel: 3, defense: 35, strategicValue: 8, fertility: 80, populationBase: 119_000, initialControllerId: 'p_xuantu' },
  { id: 'r_songhua', name: '松花', x: 815, y: 18, terrain: '平原', climate: '寒温带', river: true, port: false, cityLevel: 2, defense: 38, strategicValue: 7, fertility: 65, populationBase: 73_000, initialControllerId: 'p_xuantu' },
  { id: 'r_xianjing', name: '咸京', x: 900, y: 220, terrain: '丘陵', climate: '寒温带', river: true, port: true, cityLevel: 2, defense: 37, strategicValue: 8, fertility: 82, populationBase: 104_000, initialControllerId: 'p_xuantu' },
  { id: 'r_jeonju', name: '全州', x: 910, y: 320, terrain: '平原', climate: '暖温带', river: true, port: true, cityLevel: 2, defense: 30, strategicValue: 8, fertility: 101, populationBase: 121_000, initialControllerId: 'p_haedong' },

  { id: 'r_chaoshan', name: '潮汕', x: 575, y: 570, terrain: '海岸', climate: '湿热', river: true, port: true, cityLevel: 3, defense: 28, strategicValue: 8, fertility: 108, populationBase: 142_000, initialControllerId: 'p_canghai' },
  { id: 'r_jiaozhi', name: '交趾', x: 345, y: 650, terrain: '海岸', climate: '湿热', river: true, port: true, cityLevel: 3, defense: 31, strategicValue: 8, fertility: 116, populationBase: 157_000, initialControllerId: 'p_canghai' },
  { id: 'r_yamato', name: '大和', x: 950, y: 505, terrain: '丘陵', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 38, strategicValue: 9, fertility: 94, populationBase: 132_000, initialControllerId: 'p_yamato' },
  { id: 'r_kanto', name: '关东', x: 985, y: 305, terrain: '平原', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 36, strategicValue: 9, fertility: 91, populationBase: 137_000, initialControllerId: 'p_yamato' },

  // V0.3正式地图扩展：中原补足至40州域。
  { id: 'r_zhending', name: '真定', x: 458, y: 144, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 31, strategicValue: 8, fertility: 99, populationBase: 143_000, initialControllerId: 'p_yan' },
  { id: 'r_bohai', name: '渤海郡', x: 614, y: 168, terrain: '海岸', climate: '暖温带', river: true, port: true, cityLevel: 2, defense: 28, strategicValue: 8, fertility: 92, populationBase: 119_000, initialControllerId: 'p_yan' },
  { id: 'r_daming', name: '大名', x: 520, y: 235, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 27, strategicValue: 8, fertility: 106, populationBase: 158_000, initialControllerId: 'p_yan' },
  { id: 'r_henei', name: '河内', x: 445, y: 302, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 32, strategicValue: 9, fertility: 101, populationBase: 151_000, initialControllerId: 'p_yong' },
  { id: 'r_xuchang', name: '许昌', x: 500, y: 392, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 26, strategicValue: 9, fertility: 110, populationBase: 173_000, initialControllerId: 'p_qi' },
  { id: 'r_chenliu', name: '陈留', x: 558, y: 315, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 24, strategicValue: 8, fertility: 109, populationBase: 165_000, initialControllerId: 'p_qi' },
  { id: 'r_fenyang', name: '汾阳', x: 282, y: 235, terrain: '高原', climate: '寒温带', river: true, port: false, cityLevel: 2, defense: 41, strategicValue: 7, fertility: 73, populationBase: 94_000, initialControllerId: 'p_yan' },
  { id: 'r_yuncheng', name: '盐池', x: 286, y: 332, terrain: '丘陵', climate: '暖温带', river: true, port: false, cityLevel: 2, defense: 36, strategicValue: 8, fertility: 84, populationBase: 108_000, initialControllerId: 'p_yong' },
  { id: 'r_huazhou', name: '华州', x: 300, y: 385, terrain: '平原', climate: '暖温带', river: true, port: false, cityLevel: 3, defense: 35, strategicValue: 8, fertility: 94, populationBase: 137_000, initialControllerId: 'p_yong' },
  { id: 'r_suide', name: '绥德', x: 190, y: 205, terrain: '高原', climate: '干旱', river: false, port: false, cityLevel: 1, defense: 42, strategicValue: 6, fertility: 54, populationBase: 64_000, initialControllerId: 'p_yong' },
  { id: 'r_guyuan', name: '萧关', x: 112, y: 318, terrain: '高原', climate: '干旱', river: true, port: false, cityLevel: 2, defense: 46, strategicValue: 8, fertility: 58, populationBase: 69_000, initialControllerId: 'p_yong' },
  { id: 'r_hongnong', name: '弘农', x: 368, y: 352, terrain: '山地', climate: '暖温带', river: true, port: false, cityLevel: 2, defense: 48, strategicValue: 9, fertility: 76, populationBase: 98_000, initialControllerId: 'p_yong' },

  // 东北边疆补足至11州域。
  { id: 'r_chengde', name: '热河', x: 610, y: 48, terrain: '丘陵', climate: '寒温带', river: true, port: false, cityLevel: 2, defense: 40, strategicValue: 7, fertility: 63, populationBase: 76_000, initialControllerId: 'p_xuantu' },
  { id: 'r_jinzhou', name: '锦州', x: 665, y: 78, terrain: '海岸', climate: '寒温带', river: false, port: true, cityLevel: 2, defense: 35, strategicValue: 8, fertility: 72, populationBase: 91_000, initialControllerId: 'p_xuantu' },
  { id: 'r_yingkou', name: '营口', x: 748, y: 145, terrain: '海岸', climate: '寒温带', river: true, port: true, cityLevel: 2, defense: 31, strategicValue: 8, fertility: 76, populationBase: 99_000, initialControllerId: 'p_xuantu' },
  { id: 'r_fushun', name: '抚顺', x: 752, y: 42, terrain: '丘陵', climate: '寒温带', river: true, port: false, cityLevel: 2, defense: 39, strategicValue: 7, fertility: 67, populationBase: 83_000, initialControllerId: 'p_xuantu' },
  { id: 'r_mudan', name: '牡丹', x: 900, y: 66, terrain: '山地', climate: '寒温带', river: true, port: false, cityLevel: 1, defense: 47, strategicValue: 6, fertility: 55, populationBase: 61_000, initialControllerId: 'p_xuantu' },

  // 南方海洋补足至17州域：广东6、福建6、海南2、台湾3。
  { id: 'r_leizhou', name: '雷州', x: 420, y: 625, terrain: '海岸', climate: '湿热', river: false, port: true, cityLevel: 2, defense: 29, strategicValue: 8, fertility: 104, populationBase: 112_000, initialControllerId: 'p_canghai' },
  { id: 'r_gaozhou', name: '高州', x: 405, y: 565, terrain: '丘陵', climate: '湿热', river: true, port: true, cityLevel: 2, defense: 31, strategicValue: 7, fertility: 109, populationBase: 126_000, initialControllerId: 'p_canghai' },
  { id: 'r_nanxiong', name: '南雄', x: 505, y: 520, terrain: '山地', climate: '湿热', river: true, port: false, cityLevel: 2, defense: 44, strategicValue: 7, fertility: 93, populationBase: 101_000, initialControllerId: 'p_canghai' },
  { id: 'r_fuzhou', name: '福州', x: 690, y: 490, terrain: '海岸', climate: '湿热', river: true, port: true, cityLevel: 3, defense: 30, strategicValue: 9, fertility: 103, populationBase: 145_000, initialControllerId: 'p_minhai' },
  { id: 'r_zhangzhou', name: '漳州', x: 625, y: 585, terrain: '海岸', climate: '湿热', river: true, port: true, cityLevel: 3, defense: 29, strategicValue: 8, fertility: 108, populationBase: 139_000, initialControllerId: 'p_minhai' },
  { id: 'r_tingzhou', name: '汀州', x: 590, y: 515, terrain: '山地', climate: '湿热', river: true, port: false, cityLevel: 2, defense: 45, strategicValue: 7, fertility: 91, populationBase: 96_000, initialControllerId: 'p_minhai' },
  { id: 'r_jianning', name: '建宁', x: 635, y: 455, terrain: '山地', climate: '湿热', river: true, port: false, cityLevel: 2, defense: 46, strategicValue: 7, fertility: 94, populationBase: 103_000, initialControllerId: 'p_minhai' },
  { id: 'r_putian', name: '莆田', x: 690, y: 545, terrain: '海岸', climate: '湿热', river: false, port: true, cityLevel: 2, defense: 28, strategicValue: 8, fertility: 101, populationBase: 111_000, initialControllerId: 'p_minhai' },
  { id: 'r_qiongshan', name: '琼山', x: 500, y: 690, terrain: '岛屿', climate: '湿热', river: true, port: true, cityLevel: 2, defense: 34, strategicValue: 7, fertility: 106, populationBase: 81_000, initialControllerId: 'p_canghai' },
  { id: 'r_tainan', name: '台南', x: 720, y: 630, terrain: '岛屿', climate: '湿热', river: true, port: true, cityLevel: 2, defense: 36, strategicValue: 8, fertility: 110, populationBase: 91_000, initialControllerId: 'p_minhai' },
  { id: 'r_beigang', name: '北港', x: 780, y: 525, terrain: '岛屿', climate: '湿热', river: true, port: true, cityLevel: 2, defense: 39, strategicValue: 8, fertility: 101, populationBase: 86_000, initialControllerId: 'p_minhai' },

  // 朝鲜半岛补足至6州域。
  { id: 'r_kaesong', name: '松京', x: 845, y: 245, terrain: '丘陵', climate: '暖温带', river: true, port: false, cityLevel: 2, defense: 38, strategicValue: 8, fertility: 88, populationBase: 109_000, initialControllerId: 'p_xuantu' },
  { id: 'r_gyeongju', name: '庆州', x: 940, y: 365, terrain: '海岸', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 34, strategicValue: 9, fertility: 97, populationBase: 128_000, initialControllerId: 'p_haedong' },

  // 日本列岛补足至8州域。
  { id: 'r_chugoku', name: '山阳', x: 900, y: 420, terrain: '丘陵', climate: '暖温带', river: true, port: true, cityLevel: 2, defense: 35, strategicValue: 8, fertility: 91, populationBase: 104_000, initialControllerId: 'p_yamato' },
  { id: 'r_shikoku', name: '四国', x: 940, y: 460, terrain: '岛屿', climate: '暖温带', river: true, port: true, cityLevel: 2, defense: 38, strategicValue: 8, fertility: 89, populationBase: 92_000, initialControllerId: 'p_yamato' },
  { id: 'r_tokai', name: '东海州', x: 930, y: 350, terrain: '海岸', climate: '暖温带', river: true, port: true, cityLevel: 3, defense: 33, strategicValue: 8, fertility: 95, populationBase: 119_000, initialControllerId: 'p_yamato' },
  { id: 'r_ou', name: '奥州', x: 970, y: 220, terrain: '丘陵', climate: '寒温带', river: true, port: true, cityLevel: 2, defense: 41, strategicValue: 7, fertility: 76, populationBase: 88_000, initialControllerId: 'p_yamato' },
] as const;

export const ROUTE_DEFINITIONS: readonly RouteDefinition[] = [
  { fromRegionId: 'r_lingzhou', toRegionId: 'r_yanan', kind: '山道', supplyCapacity: 7_000 },
  { fromRegionId: 'r_yanan', toRegionId: 'r_changan', kind: '山道', supplyCapacity: 8_000 },
  { fromRegionId: 'r_yanan', toRegionId: 'r_hedong', kind: '山道', supplyCapacity: 6_500 },
  { fromRegionId: 'r_changan', toRegionId: 'r_hedong', kind: '山道', supplyCapacity: 9_000 },
  { fromRegionId: 'r_changan', toRegionId: 'r_nanyang', kind: '山道', supplyCapacity: 7_500 },
  { fromRegionId: 'r_hedong', toRegionId: 'r_jinyang', kind: '河道', supplyCapacity: 12_000 },
  { fromRegionId: 'r_hedong', toRegionId: 'r_luoyang', kind: '河道', supplyCapacity: 14_000 },
  { fromRegionId: 'r_jinyang', toRegionId: 'r_shangdang', kind: '道路', supplyCapacity: 10_000 },
  { fromRegionId: 'r_shangdang', toRegionId: 'r_luoyang', kind: '山道', supplyCapacity: 7_000 },
  { fromRegionId: 'r_shangdang', toRegionId: 'r_yecheng', kind: '道路', supplyCapacity: 10_000 },
  { fromRegionId: 'r_jinyang', toRegionId: 'r_changshan', kind: '道路', supplyCapacity: 11_000 },
  { fromRegionId: 'r_changshan', toRegionId: 'r_yanjing', kind: '道路', supplyCapacity: 14_000 },
  { fromRegionId: 'r_changshan', toRegionId: 'r_yecheng', kind: '道路', supplyCapacity: 14_000 },
  { fromRegionId: 'r_yanjing', toRegionId: 'r_jinmen', kind: '河道', supplyCapacity: 16_000 },
  { fromRegionId: 'r_jinmen', toRegionId: 'r_yecheng', kind: '河道', supplyCapacity: 13_000 },
  { fromRegionId: 'r_yanjing', toRegionId: 'r_liaoxi', kind: '道路', supplyCapacity: 10_000 },
  { fromRegionId: 'r_jinmen', toRegionId: 'r_liaoxi', kind: '道路', supplyCapacity: 9_000 },
  { fromRegionId: 'r_yecheng', toRegionId: 'r_kaifeng', kind: '河道', supplyCapacity: 16_000 },
  { fromRegionId: 'r_yecheng', toRegionId: 'r_qizhou', kind: '道路', supplyCapacity: 15_000 },
  { fromRegionId: 'r_changshan', toRegionId: 'r_qizhou', kind: '道路', supplyCapacity: 12_000 },
  { fromRegionId: 'r_luoyang', toRegionId: 'r_kaifeng', kind: '河道', supplyCapacity: 18_000 },
  { fromRegionId: 'r_luoyang', toRegionId: 'r_nanyang', kind: '道路', supplyCapacity: 13_000 },
  { fromRegionId: 'r_kaifeng', toRegionId: 'r_runan', kind: '河道', supplyCapacity: 16_000 },
  { fromRegionId: 'r_kaifeng', toRegionId: 'r_qizhou', kind: '河道', supplyCapacity: 18_000 },
  { fromRegionId: 'r_runan', toRegionId: 'r_nanyang', kind: '道路', supplyCapacity: 13_000 },
  { fromRegionId: 'r_runan', toRegionId: 'r_langya', kind: '道路', supplyCapacity: 12_000 },
  { fromRegionId: 'r_qizhou', toRegionId: 'r_qingzhou', kind: '道路', supplyCapacity: 15_000 },
  { fromRegionId: 'r_qizhou', toRegionId: 'r_langya', kind: '道路', supplyCapacity: 14_000 },
  { fromRegionId: 'r_qingzhou', toRegionId: 'r_dengzhou', kind: '道路', supplyCapacity: 11_000 },
  { fromRegionId: 'r_dengzhou', toRegionId: 'r_langya', kind: '道路', supplyCapacity: 10_000 },
  { fromRegionId: 'r_liaoxi', toRegionId: 'r_liaodong', kind: '道路', supplyCapacity: 10_000 },
  { fromRegionId: 'r_liaodong', toRegionId: 'r_jilin', kind: '道路', supplyCapacity: 9_000 },
  { fromRegionId: 'r_jilin', toRegionId: 'r_changbai', kind: '山道', supplyCapacity: 5_000 },
  { fromRegionId: 'r_liaodong', toRegionId: 'r_pyongyang', kind: '道路', supplyCapacity: 9_000 },
  { fromRegionId: 'r_pyongyang', toRegionId: 'r_hanjing', kind: '道路', supplyCapacity: 10_000 },
  { fromRegionId: 'r_dengzhou', toRegionId: 'r_pyongyang', kind: '海峡', supplyCapacity: 5_500 },
  { fromRegionId: 'r_langya', toRegionId: 'r_quanzhou', kind: '海峡', supplyCapacity: 4_500 },
  { fromRegionId: 'r_nanyang', toRegionId: 'r_guangzhou', kind: '山道', supplyCapacity: 6_500 },
  { fromRegionId: 'r_runan', toRegionId: 'r_quanzhou', kind: '山道', supplyCapacity: 6_000 },
  { fromRegionId: 'r_quanzhou', toRegionId: 'r_guangzhou', kind: '道路', supplyCapacity: 12_000 },
  { fromRegionId: 'r_guangzhou', toRegionId: 'r_hainan', kind: '海峡', supplyCapacity: 6_000 },
  { fromRegionId: 'r_quanzhou', toRegionId: 'r_taiwan', kind: '海峡', supplyCapacity: 5_500 },
  { fromRegionId: 'r_taiwan', toRegionId: 'r_tsukushi', kind: '海峡', supplyCapacity: 4_500 },
  { fromRegionId: 'r_hanjing', toRegionId: 'r_tsukushi', kind: '海峡', supplyCapacity: 5_000 },
  { fromRegionId: 'r_tsukushi', toRegionId: 'r_naniwa', kind: '海峡', supplyCapacity: 7_000 },
  { fromRegionId: 'r_datong', toRegionId: 'r_jinyang', kind: '山道', supplyCapacity: 7_000 },
  { fromRegionId: 'r_datong', toRegionId: 'r_changshan', kind: '山道', supplyCapacity: 7_500 },
  { fromRegionId: 'r_hejian', toRegionId: 'r_jinmen', kind: '河道', supplyCapacity: 13_000 },
  { fromRegionId: 'r_hejian', toRegionId: 'r_yecheng', kind: '河道', supplyCapacity: 13_500 },
  { fromRegionId: 'r_yuyang', toRegionId: 'r_yanjing', kind: '道路', supplyCapacity: 11_000 },
  { fromRegionId: 'r_yuyang', toRegionId: 'r_liaoxi', kind: '道路', supplyCapacity: 9_000 },
  { fromRegionId: 'r_donglai', toRegionId: 'r_qingzhou', kind: '道路', supplyCapacity: 11_500 },
  { fromRegionId: 'r_donglai', toRegionId: 'r_dengzhou', kind: '海峡', supplyCapacity: 7_000 },
  { fromRegionId: 'r_pengcheng', toRegionId: 'r_langya', kind: '道路', supplyCapacity: 12_000 },
  { fromRegionId: 'r_pengcheng', toRegionId: 'r_runan', kind: '河道', supplyCapacity: 14_000 },
  { fromRegionId: 'r_huaiyang', toRegionId: 'r_pengcheng', kind: '河道', supplyCapacity: 13_000 },
  { fromRegionId: 'r_huaiyang', toRegionId: 'r_runan', kind: '河道', supplyCapacity: 13_500 },
  { fromRegionId: 'r_beidi', toRegionId: 'r_lingzhou', kind: '山道', supplyCapacity: 6_500 },
  { fromRegionId: 'r_beidi', toRegionId: 'r_changan', kind: '山道', supplyCapacity: 7_000 },
  { fromRegionId: 'r_tianshui', toRegionId: 'r_beidi', kind: '山道', supplyCapacity: 6_000 },
  { fromRegionId: 'r_tianshui', toRegionId: 'r_changan', kind: '山道', supplyCapacity: 7_500 },
  { fromRegionId: 'r_hanzhong', toRegionId: 'r_tianshui', kind: '山道', supplyCapacity: 6_000 },
  { fromRegionId: 'r_hanzhong', toRegionId: 'r_nanyang', kind: '山道', supplyCapacity: 7_500 },
  { fromRegionId: 'r_shangluo', toRegionId: 'r_changan', kind: '山道', supplyCapacity: 7_500 },
  { fromRegionId: 'r_shangluo', toRegionId: 'r_hanzhong', kind: '山道', supplyCapacity: 6_500 },
  { fromRegionId: 'r_shangluo', toRegionId: 'r_nanyang', kind: '山道', supplyCapacity: 7_000 },
  { fromRegionId: 'r_shenyang', toRegionId: 'r_liaoxi', kind: '道路', supplyCapacity: 9_500 },
  { fromRegionId: 'r_shenyang', toRegionId: 'r_liaodong', kind: '河道', supplyCapacity: 10_000 },
  { fromRegionId: 'r_songhua', toRegionId: 'r_jilin', kind: '河道', supplyCapacity: 7_500 },
  { fromRegionId: 'r_xianjing', toRegionId: 'r_pyongyang', kind: '道路', supplyCapacity: 9_000 },
  { fromRegionId: 'r_xianjing', toRegionId: 'r_hanjing', kind: '道路', supplyCapacity: 8_000 },
  { fromRegionId: 'r_jeonju', toRegionId: 'r_hanjing', kind: '道路', supplyCapacity: 9_000 },
  { fromRegionId: 'r_jeonju', toRegionId: 'r_tsukushi', kind: '海峡', supplyCapacity: 5_000 },
  { fromRegionId: 'r_chaoshan', toRegionId: 'r_quanzhou', kind: '道路', supplyCapacity: 11_000 },
  { fromRegionId: 'r_chaoshan', toRegionId: 'r_guangzhou', kind: '道路', supplyCapacity: 11_500 },
  { fromRegionId: 'r_jiaozhi', toRegionId: 'r_guangzhou', kind: '道路', supplyCapacity: 9_000 },
  { fromRegionId: 'r_jiaozhi', toRegionId: 'r_hainan', kind: '海峡', supplyCapacity: 5_500 },
  { fromRegionId: 'r_yamato', toRegionId: 'r_tsukushi', kind: '海峡', supplyCapacity: 6_500 },
  { fromRegionId: 'r_yamato', toRegionId: 'r_naniwa', kind: '道路', supplyCapacity: 9_500 },
  { fromRegionId: 'r_kanto', toRegionId: 'r_naniwa', kind: '道路', supplyCapacity: 8_500 },
  { fromRegionId: 'r_kanto', toRegionId: 'r_yamato', kind: '道路', supplyCapacity: 8_500 },

  // V0.3新增陆边使用内容稳定ID；海峡只由PortLink与SeaLane承担。
  { id: 'land_zhending_changshan', fromRegionId: 'r_zhending', toRegionId: 'r_changshan', kind: '道路', supplyCapacity: 13_000 },
  { id: 'land_zhending_yanjing', fromRegionId: 'r_zhending', toRegionId: 'r_yanjing', kind: '道路', supplyCapacity: 12_000 },
  { id: 'river_bohai_jinmen', fromRegionId: 'r_bohai', toRegionId: 'r_jinmen', kind: '河道', supplyCapacity: 14_000 },
  { id: 'land_bohai_hejian', fromRegionId: 'r_bohai', toRegionId: 'r_hejian', kind: '道路', supplyCapacity: 11_000 },
  { id: 'river_daming_hejian', fromRegionId: 'r_daming', toRegionId: 'r_hejian', kind: '河道', supplyCapacity: 13_000 },
  { id: 'river_daming_yecheng', fromRegionId: 'r_daming', toRegionId: 'r_yecheng', kind: '河道', supplyCapacity: 14_000 },
  { id: 'river_henei_luoyang', fromRegionId: 'r_henei', toRegionId: 'r_luoyang', kind: '河道', supplyCapacity: 15_000 },
  { id: 'river_henei_hedong', fromRegionId: 'r_henei', toRegionId: 'r_hedong', kind: '河道', supplyCapacity: 13_000 },
  { id: 'land_xuchang_kaifeng', fromRegionId: 'r_xuchang', toRegionId: 'r_kaifeng', kind: '道路', supplyCapacity: 14_000 },
  { id: 'land_xuchang_runan', fromRegionId: 'r_xuchang', toRegionId: 'r_runan', kind: '道路', supplyCapacity: 13_000 },
  { id: 'river_chenliu_kaifeng', fromRegionId: 'r_chenliu', toRegionId: 'r_kaifeng', kind: '河道', supplyCapacity: 16_000 },
  { id: 'land_chenliu_qizhou', fromRegionId: 'r_chenliu', toRegionId: 'r_qizhou', kind: '道路', supplyCapacity: 13_500 },
  { id: 'river_fenyang_jinyang', fromRegionId: 'r_fenyang', toRegionId: 'r_jinyang', kind: '河道', supplyCapacity: 10_000 },
  { id: 'land_fenyang_hedong', fromRegionId: 'r_fenyang', toRegionId: 'r_hedong', kind: '道路', supplyCapacity: 9_000 },
  { id: 'river_yuncheng_hedong', fromRegionId: 'r_yuncheng', toRegionId: 'r_hedong', kind: '河道', supplyCapacity: 12_000 },
  { id: 'land_yuncheng_changan', fromRegionId: 'r_yuncheng', toRegionId: 'r_changan', kind: '道路', supplyCapacity: 10_000 },
  { id: 'land_huazhou_changan', fromRegionId: 'r_huazhou', toRegionId: 'r_changan', kind: '道路', supplyCapacity: 12_000 },
  { id: 'mountain_huazhou_shangluo', fromRegionId: 'r_huazhou', toRegionId: 'r_shangluo', kind: '山道', supplyCapacity: 7_500 },
  { id: 'mountain_suide_yanan', fromRegionId: 'r_suide', toRegionId: 'r_yanan', kind: '山道', supplyCapacity: 6_500 },
  { id: 'mountain_suide_lingzhou', fromRegionId: 'r_suide', toRegionId: 'r_lingzhou', kind: '山道', supplyCapacity: 5_500 },
  { id: 'mountain_guyuan_lingzhou', fromRegionId: 'r_guyuan', toRegionId: 'r_lingzhou', kind: '山道', supplyCapacity: 6_000 },
  { id: 'mountain_guyuan_beidi', fromRegionId: 'r_guyuan', toRegionId: 'r_beidi', kind: '山道', supplyCapacity: 6_500 },
  { id: 'mountain_hongnong_luoyang', fromRegionId: 'r_hongnong', toRegionId: 'r_luoyang', kind: '山道', supplyCapacity: 8_000 },
  { id: 'mountain_hongnong_changan', fromRegionId: 'r_hongnong', toRegionId: 'r_changan', kind: '山道', supplyCapacity: 8_500 },

  { id: 'land_chengde_yuyang', fromRegionId: 'r_chengde', toRegionId: 'r_yuyang', kind: '山道', supplyCapacity: 7_500 },
  { id: 'land_chengde_liaoxi', fromRegionId: 'r_chengde', toRegionId: 'r_liaoxi', kind: '道路', supplyCapacity: 8_000 },
  { id: 'land_jinzhou_liaoxi', fromRegionId: 'r_jinzhou', toRegionId: 'r_liaoxi', kind: '道路', supplyCapacity: 9_000 },
  { id: 'land_jinzhou_shenyang', fromRegionId: 'r_jinzhou', toRegionId: 'r_shenyang', kind: '道路', supplyCapacity: 9_500 },
  { id: 'river_yingkou_liaodong', fromRegionId: 'r_yingkou', toRegionId: 'r_liaodong', kind: '河道', supplyCapacity: 11_000 },
  { id: 'river_yingkou_shenyang', fromRegionId: 'r_yingkou', toRegionId: 'r_shenyang', kind: '河道', supplyCapacity: 10_000 },
  { id: 'land_fushun_shenyang', fromRegionId: 'r_fushun', toRegionId: 'r_shenyang', kind: '道路', supplyCapacity: 8_000 },
  { id: 'mountain_fushun_jilin', fromRegionId: 'r_fushun', toRegionId: 'r_jilin', kind: '山道', supplyCapacity: 6_500 },
  { id: 'mountain_mudan_jilin', fromRegionId: 'r_mudan', toRegionId: 'r_jilin', kind: '山道', supplyCapacity: 6_000 },
  { id: 'mountain_mudan_changbai', fromRegionId: 'r_mudan', toRegionId: 'r_changbai', kind: '山道', supplyCapacity: 5_500 },

  { id: 'land_leizhou_guangzhou', fromRegionId: 'r_leizhou', toRegionId: 'r_guangzhou', kind: '道路', supplyCapacity: 9_000 },
  { id: 'land_leizhou_gaozhou', fromRegionId: 'r_leizhou', toRegionId: 'r_gaozhou', kind: '道路', supplyCapacity: 8_500 },
  { id: 'land_gaozhou_guangzhou', fromRegionId: 'r_gaozhou', toRegionId: 'r_guangzhou', kind: '道路', supplyCapacity: 10_000 },
  { id: 'land_gaozhou_jiaozhi', fromRegionId: 'r_gaozhou', toRegionId: 'r_jiaozhi', kind: '道路', supplyCapacity: 8_000 },
  { id: 'mountain_nanxiong_guangzhou', fromRegionId: 'r_nanxiong', toRegionId: 'r_guangzhou', kind: '山道', supplyCapacity: 7_500 },
  { id: 'mountain_nanxiong_chaoshan', fromRegionId: 'r_nanxiong', toRegionId: 'r_chaoshan', kind: '山道', supplyCapacity: 7_000 },
  { id: 'land_fuzhou_quanzhou', fromRegionId: 'r_fuzhou', toRegionId: 'r_quanzhou', kind: '道路', supplyCapacity: 11_000 },
  { id: 'mountain_fuzhou_jianning', fromRegionId: 'r_fuzhou', toRegionId: 'r_jianning', kind: '山道', supplyCapacity: 7_000 },
  { id: 'land_fuzhou_putian', fromRegionId: 'r_fuzhou', toRegionId: 'r_putian', kind: '道路', supplyCapacity: 10_000 },
  { id: 'land_zhangzhou_quanzhou', fromRegionId: 'r_zhangzhou', toRegionId: 'r_quanzhou', kind: '道路', supplyCapacity: 10_500 },
  { id: 'mountain_zhangzhou_tingzhou', fromRegionId: 'r_zhangzhou', toRegionId: 'r_tingzhou', kind: '山道', supplyCapacity: 7_000 },
  { id: 'mountain_tingzhou_jianning', fromRegionId: 'r_tingzhou', toRegionId: 'r_jianning', kind: '山道', supplyCapacity: 6_500 },
  { id: 'mountain_tingzhou_chaoshan', fromRegionId: 'r_tingzhou', toRegionId: 'r_chaoshan', kind: '山道', supplyCapacity: 6_500 },
  { id: 'land_putian_quanzhou', fromRegionId: 'r_putian', toRegionId: 'r_quanzhou', kind: '道路', supplyCapacity: 9_500 },
  { id: 'land_hainan_qiongshan', fromRegionId: 'r_hainan', toRegionId: 'r_qiongshan', kind: '道路', supplyCapacity: 7_500 },
  { id: 'land_taiwan_tainan', fromRegionId: 'r_taiwan', toRegionId: 'r_tainan', kind: '道路', supplyCapacity: 8_500 },
  { id: 'land_taiwan_beigang', fromRegionId: 'r_taiwan', toRegionId: 'r_beigang', kind: '道路', supplyCapacity: 8_000 },
  { id: 'land_tainan_beigang', fromRegionId: 'r_tainan', toRegionId: 'r_beigang', kind: '道路', supplyCapacity: 7_500 },

  { id: 'land_kaesong_pyongyang', fromRegionId: 'r_kaesong', toRegionId: 'r_pyongyang', kind: '道路', supplyCapacity: 9_000 },
  { id: 'land_kaesong_hanjing', fromRegionId: 'r_kaesong', toRegionId: 'r_hanjing', kind: '道路', supplyCapacity: 10_000 },
  { id: 'land_gyeongju_hanjing', fromRegionId: 'r_gyeongju', toRegionId: 'r_hanjing', kind: '道路', supplyCapacity: 9_000 },
  { id: 'land_gyeongju_jeonju', fromRegionId: 'r_gyeongju', toRegionId: 'r_jeonju', kind: '道路', supplyCapacity: 9_500 },

  { id: 'land_chugoku_naniwa', fromRegionId: 'r_chugoku', toRegionId: 'r_naniwa', kind: '道路', supplyCapacity: 9_000 },
  { id: 'land_tokai_naniwa', fromRegionId: 'r_tokai', toRegionId: 'r_naniwa', kind: '道路', supplyCapacity: 9_500 },
  { id: 'land_tokai_kanto', fromRegionId: 'r_tokai', toRegionId: 'r_kanto', kind: '道路', supplyCapacity: 9_000 },
  { id: 'land_ou_kanto', fromRegionId: 'r_ou', toRegionId: 'r_kanto', kind: '道路', supplyCapacity: 7_500 },
] as const;

/** Static grouping is kept beside content so the 82-region contract is testable. */
export const REGION_GROUPS = {
  中原大陆: [
    'r_yanjing', 'r_jinmen', 'r_changshan', 'r_yecheng', 'r_jinyang', 'r_shangdang',
    'r_qizhou', 'r_qingzhou', 'r_dengzhou', 'r_langya', 'r_kaifeng', 'r_runan',
    'r_luoyang', 'r_nanyang', 'r_hedong', 'r_changan', 'r_yanan', 'r_lingzhou',
    'r_datong', 'r_hejian', 'r_yuyang', 'r_donglai', 'r_pengcheng', 'r_huaiyang',
    'r_beidi', 'r_tianshui', 'r_hanzhong', 'r_shangluo',
    'r_zhending', 'r_bohai', 'r_daming', 'r_henei', 'r_xuchang', 'r_chenliu',
    'r_fenyang', 'r_yuncheng', 'r_huazhou', 'r_suide', 'r_guyuan', 'r_hongnong',
  ],
  东北边疆: [
    'r_liaoxi', 'r_liaodong', 'r_jilin', 'r_changbai', 'r_shenyang', 'r_songhua',
    'r_chengde', 'r_jinzhou', 'r_yingkou', 'r_fushun', 'r_mudan',
  ],
  南方海洋: [
    'r_quanzhou', 'r_guangzhou', 'r_hainan', 'r_taiwan', 'r_chaoshan', 'r_jiaozhi',
    'r_leizhou', 'r_gaozhou', 'r_nanxiong', 'r_fuzhou', 'r_zhangzhou', 'r_tingzhou',
    'r_jianning', 'r_putian', 'r_qiongshan', 'r_tainan', 'r_beigang',
  ],
  朝鲜半岛: ['r_pyongyang', 'r_hanjing', 'r_xianjing', 'r_jeonju', 'r_kaesong', 'r_gyeongju'],
  日本列岛: ['r_tsukushi', 'r_naniwa', 'r_yamato', 'r_kanto', 'r_chugoku', 'r_shikoku', 'r_tokai', 'r_ou'],
} as const;

export const SEA_ZONE_DEFINITIONS: readonly SeaZoneDefinition[] = [
  { id: 'sea_bohai', name: '环内海', x: 650, y: 150, climate: '内海', stormRisk: 12, piracy: 15 },
  { id: 'sea_shandong', name: '山东外海', x: 735, y: 320, climate: '北方海', stormRisk: 20, piracy: 20 },
  { id: 'sea_north_strait', name: '北方海峡', x: 810, y: 165, climate: '北方海', stormRisk: 23, piracy: 17 },
  { id: 'sea_fujian', name: '福建外海', x: 700, y: 500, climate: '季风海', stormRisk: 29, piracy: 27 },
  { id: 'sea_taiwan', name: '台湾海峡', x: 740, y: 575, climate: '季风海', stormRisk: 34, piracy: 24 },
  { id: 'sea_guangdong', name: '广东外海', x: 520, y: 625, climate: '季风海', stormRisk: 31, piracy: 30 },
  { id: 'sea_qiongzhou', name: '琼州海峡', x: 455, y: 680, climate: '内海', stormRisk: 25, piracy: 26 },
  { id: 'sea_korea', name: '朝鲜海峡', x: 875, y: 390, climate: '北方海', stormRisk: 27, piracy: 22 },
  { id: 'sea_japan_inland', name: '日本内海', x: 925, y: 445, climate: '内海', stormRisk: 18, piracy: 29 },
  { id: 'sea_east_ocean', name: '东部外洋', x: 990, y: 520, climate: '外洋', stormRisk: 42, piracy: 18 },
] as const;

export const SEA_LANE_DEFINITIONS: readonly SeaLaneDefinition[] = [
  { id: 'lane_bohai_shandong', fromSeaZoneId: 'sea_bohai', toSeaZoneId: 'sea_shandong', distance: 4, capacity: 32_000, baseRisk: 10, strait: false },
  { id: 'lane_bohai_north', fromSeaZoneId: 'sea_bohai', toSeaZoneId: 'sea_north_strait', distance: 3, capacity: 26_000, baseRisk: 9, strait: true },
  { id: 'lane_shandong_north', fromSeaZoneId: 'sea_shandong', toSeaZoneId: 'sea_north_strait', distance: 4, capacity: 28_000, baseRisk: 12, strait: false },
  { id: 'lane_shandong_fujian', fromSeaZoneId: 'sea_shandong', toSeaZoneId: 'sea_fujian', distance: 8, capacity: 30_000, baseRisk: 18, strait: false },
  { id: 'lane_fujian_taiwan', fromSeaZoneId: 'sea_fujian', toSeaZoneId: 'sea_taiwan', distance: 3, capacity: 38_000, baseRisk: 14, strait: true },
  { id: 'lane_fujian_guangdong', fromSeaZoneId: 'sea_fujian', toSeaZoneId: 'sea_guangdong', distance: 6, capacity: 30_000, baseRisk: 17, strait: false },
  { id: 'lane_taiwan_guangdong', fromSeaZoneId: 'sea_taiwan', toSeaZoneId: 'sea_guangdong', distance: 5, capacity: 28_000, baseRisk: 19, strait: false },
  { id: 'lane_guangdong_qiongzhou', fromSeaZoneId: 'sea_guangdong', toSeaZoneId: 'sea_qiongzhou', distance: 2, capacity: 25_000, baseRisk: 11, strait: true },
  { id: 'lane_north_korea', fromSeaZoneId: 'sea_north_strait', toSeaZoneId: 'sea_korea', distance: 5, capacity: 27_000, baseRisk: 15, strait: false },
  { id: 'lane_taiwan_korea', fromSeaZoneId: 'sea_taiwan', toSeaZoneId: 'sea_korea', distance: 7, capacity: 25_000, baseRisk: 20, strait: false },
  { id: 'lane_korea_japan', fromSeaZoneId: 'sea_korea', toSeaZoneId: 'sea_japan_inland', distance: 2, capacity: 34_000, baseRisk: 12, strait: true },
  { id: 'lane_japan_east', fromSeaZoneId: 'sea_japan_inland', toSeaZoneId: 'sea_east_ocean', distance: 5, capacity: 29_000, baseRisk: 21, strait: false },
  { id: 'lane_taiwan_east', fromSeaZoneId: 'sea_taiwan', toSeaZoneId: 'sea_east_ocean', distance: 6, capacity: 27_000, baseRisk: 23, strait: false },
  { id: 'lane_fujian_east', fromSeaZoneId: 'sea_fujian', toSeaZoneId: 'sea_east_ocean', distance: 8, capacity: 22_000, baseRisk: 26, strait: false },
] as const;

const portLink = (regionId: string, seaZoneId: string, capacity: number, distance = 1): PortLinkDefinition => ({
  id: `portlink_${regionId.slice(2)}_${seaZoneId.slice(4)}`,
  regionId,
  seaZoneId,
  capacity,
  distance,
});

export const PORT_LINK_DEFINITIONS: readonly PortLinkDefinition[] = [
  portLink('r_jinmen', 'sea_bohai', 22_000),
  portLink('r_bohai', 'sea_bohai', 18_000),
  portLink('r_liaoxi', 'sea_bohai', 14_000),
  portLink('r_jinzhou', 'sea_bohai', 16_000),
  portLink('r_yingkou', 'sea_bohai', 17_000),
  portLink('r_qingzhou', 'sea_shandong', 18_000),
  portLink('r_dengzhou', 'sea_shandong', 17_000),
  portLink('r_donglai', 'sea_shandong', 15_000),
  portLink('r_langya', 'sea_shandong', 19_000),
  portLink('r_liaodong', 'sea_north_strait', 18_000),
  portLink('r_pyongyang', 'sea_north_strait', 16_000),
  portLink('r_xianjing', 'sea_north_strait', 14_000),
  portLink('r_quanzhou', 'sea_fujian', 23_000),
  portLink('r_fuzhou', 'sea_fujian', 22_000),
  portLink('r_zhangzhou', 'sea_fujian', 19_000),
  portLink('r_putian', 'sea_fujian', 15_000),
  portLink('r_taiwan', 'sea_taiwan', 17_000),
  portLink('r_tainan', 'sea_taiwan', 16_000),
  portLink('r_beigang', 'sea_taiwan', 15_000),
  portLink('r_guangzhou', 'sea_guangdong', 26_000),
  portLink('r_chaoshan', 'sea_guangdong', 19_000),
  portLink('r_jiaozhi', 'sea_guangdong', 17_000),
  portLink('r_gaozhou', 'sea_guangdong', 14_000),
  portLink('r_leizhou', 'sea_guangdong', 15_000),
  portLink('r_leizhou', 'sea_qiongzhou', 14_000),
  portLink('r_hainan', 'sea_qiongzhou', 13_000),
  portLink('r_qiongshan', 'sea_qiongzhou', 13_000),
  portLink('r_hanjing', 'sea_korea', 19_000),
  portLink('r_jeonju', 'sea_korea', 15_000),
  portLink('r_gyeongju', 'sea_korea', 18_000),
  portLink('r_tsukushi', 'sea_korea', 18_000),
  portLink('r_tsukushi', 'sea_japan_inland', 17_000),
  portLink('r_naniwa', 'sea_japan_inland', 22_000),
  portLink('r_yamato', 'sea_japan_inland', 20_000),
  portLink('r_chugoku', 'sea_japan_inland', 16_000),
  portLink('r_shikoku', 'sea_japan_inland', 15_000),
  portLink('r_kanto', 'sea_east_ocean', 21_000),
  portLink('r_tokai', 'sea_east_ocean', 18_000),
  portLink('r_ou', 'sea_east_ocean', 14_000),
  portLink('r_yamato', 'sea_east_ocean', 13_000, 2),
] as const;
